service: messagebird-serverless

plugins:
  - serverless-webpack
  - serverless-secrets-plugin

custom:
  
  webpackIncludeModules:
    packagePath: './package.json'
  
provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  environment:
    ACCESS_KEY: secrets.dev.ACCESS_KEY

functions:
  sendSms:
    handler: handler.sendSms


