service: messagebird-serverless

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules:
    packagePath: './package.json'
  
provider:
  name: aws
  runtime: nodejs6.10

functions:
  hello:
    handler: handler.hello


